### ISSUE TITLE
CSS: pas op met aannames qua support

### ISSUE THREAD

**Issue by KrijnHoetmer** [jaimiederijk/browser_technologies#4]
Specifiek bij dit voorbeeld:

``` CSS
nav ul li {
    display: inline-block;
    background-color: rgba(0,200,10,1);
    width: calc(50% - 0.2rem);
    height: 2rem;
}
```

Wat als `rgba()`, `calc()` of `rem` niet ondersteund wordt?
